name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Ejecuta una vez al día
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: deveder-sys # Cambia esto por tu nombre de usuario
          svg_out_path: dist/snake.svg

      - uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

